/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyectonetbean.Ventanas.PanelesGestion;

import com.mycompany.proyectonetbean.Clases.Cliente;
import com.mycompany.proyectonetbean.Clases.Empleado;
import com.mycompany.proyectonetbean.ProyectoNetBean;

import javax.swing.*;
import javax.swing.border.LineBorder;
import java.awt.*;
import java.sql.SQLException;
import java.util.Date;

/**
 *
 * @author mario
 */
public class Anadir_empleado extends javax.swing.JPanel {

    Boolean error = false;

    /**
     * Creates new form Anadir_empleado
     */
    public Anadir_empleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        n_edad = new javax.swing.JSpinner();
        c_fecha_nac = new com.toedter.calendar.JCalendar();
        jLabel6 = new javax.swing.JLabel();
        c_fecha_contrato = new com.toedter.calendar.JCalendar();
        jLabel7 = new javax.swing.JLabel();
        t_nacionalidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cb_cargo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        t_name = new javax.swing.JTextField();
        t_apellido = new javax.swing.JTextField();
        t_dni = new javax.swing.JTextField();
        b_anadir = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1071, 585));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Añadir empleados");

        n_edad.setPreferredSize(new java.awt.Dimension(84, 22));
        n_edad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n_edadMouseClicked(evt);
            }
        });

        jLabel6.setText("Fecha nacimiento:");

        jLabel7.setText("Fecha contratacion:");

        t_nacionalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_nacionalidadActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre:");

        jLabel8.setText("Nacionalidad:");

        jLabel3.setText("Apellido");

        jLabel9.setText("Cargo:");

        jLabel4.setText("DNI:");

        cb_cargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente", "Trabajador", " " }));
        cb_cargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_cargoActionPerformed(evt);
            }
        });

        jLabel5.setText("Edad:");

        t_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_nameActionPerformed(evt);
            }
        });

        t_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_apellidoActionPerformed(evt);
            }
        });

        t_dni.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                try {
                    t_dniFocusLost(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });
        t_dni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_dniActionPerformed(evt);
            }
        });

        b_anadir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_anadir.setText("Añadir");
        b_anadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_anadirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(b_anadir, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGap(441, 441, 441))
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(t_nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(cb_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(c_fecha_nac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t_name)
                            .addComponent(t_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(n_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t_apellido)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c_fecha_contrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(t_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(n_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(t_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(t_dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(c_fecha_nac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_fecha_contrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(cb_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(b_anadir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void t_nacionalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_nacionalidadActionPerformed
        // TODO add your handling code here:
                t_nacionalidad.setBorder(new LineBorder(Color.black,1));
    }//GEN-LAST:event_t_nacionalidadActionPerformed

    private void cb_cargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_cargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_cargoActionPerformed

    private void b_anadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_anadirActionPerformed
        // TODO add your handling code here:
        int cont = 0;
        if(t_name.getText().isEmpty() ){
            cont++;
            t_name.setBorder(new LineBorder(Color.red,1));
        }
        if(t_apellido.getText().isEmpty() ){
            cont++;
            t_apellido.setBorder(new LineBorder(Color.red,1));
        }
        if(t_dni.getText().isEmpty() ){
            cont++;
            t_dni.setBorder(new LineBorder(Color.red,1));
        }
        if(n_edad.getValue().toString().equals('0') ){
            cont++;
            n_edad.setBorder(new LineBorder(Color.red,1));
        }
        if(t_nacionalidad.getText().isEmpty() ){
            cont++;
            t_dni.setBorder(new LineBorder(Color.red,1));
        }
        if(c_fecha_nac.getDate().after(new Date())){
            cont++;
            c_fecha_nac.setBorder(new LineBorder(Color.red,1));
        }
        if(c_fecha_contrato.getDate().after(new Date())){
            cont++;
            c_fecha_nac.setBorder(new LineBorder(Color.red,1));
        }

        if (cont == 0 && !error) {
            Empleado emple = new Empleado(t_name.getText(), t_apellido.getText(),t_dni.getText(),Integer.parseInt(n_edad.getValue().toString()), t_nacionalidad.getText(),c_fecha_nac.getDate(), c_fecha_contrato.getDate(),cb_cargo.getSelectedIndex());
            ProyectoNetBean.insertEmpleado(emple);
        }
        else{
            JOptionPane.showMessageDialog(null, "Revisa los datos");

        }
    }//GEN-LAST:event_b_anadirActionPerformed

    private void t_dniFocusLost(java.awt.event.FocusEvent evt) throws SQLException {//GEN-FIRST:event_t_dniFocusLost
        // TODO add your handling code here:
        String dni = t_dni.getText();
        error = ProyectoNetBean.getDni(dni);
        if (error){
            t_dni.setBorder(new LineBorder(Color.red,1));
            t_dni.setText("DNI ya utilizado");
            t_dni.setForeground(Color.red);

        }
    }//GEN-LAST:event_t_dniFocusLost

    private void t_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_nameActionPerformed
        // TODO add your handling code here:
        t_name.setBorder(new LineBorder(Color.black,1));

    }//GEN-LAST:event_t_nameActionPerformed

    private void t_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_apellidoActionPerformed
        // TODO add your handling code here:
        t_apellido.setBorder(new LineBorder(Color.black,1));

    }//GEN-LAST:event_t_apellidoActionPerformed

    private void t_dniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_dniActionPerformed
        // TODO add your handling code here:
        t_dni.setBorder(new LineBorder(Color.black,1));

    }//GEN-LAST:event_t_dniActionPerformed

    private void n_edadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n_edadMouseClicked
        // TODO add your handling code here:
        n_edad.setBorder(new LineBorder(Color.black,1));

    }//GEN-LAST:event_n_edadMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_anadir;
    private com.toedter.calendar.JCalendar c_fecha_contrato;
    private com.toedter.calendar.JCalendar c_fecha_nac;
    private javax.swing.JComboBox<String> cb_cargo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner n_edad;
    private javax.swing.JTextField t_apellido;
    private javax.swing.JTextField t_dni;
    private javax.swing.JTextField t_nacionalidad;
    private javax.swing.JTextField t_name;
    // End of variables declaration//GEN-END:variables
}
