/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyectonetbean.Ventanas.PanelesGestion;

import com.mycompany.proyectonetbean.Clases.Cliente;
import com.mycompany.proyectonetbean.ProyectoNetBean;

import javax.swing.*;
import javax.swing.border.LineBorder;
import java.awt.*;
import java.sql.SQLException;

/**
 *
 * @author mario
 */
public class Anadir_cliente extends javax.swing.JPanel {
    Boolean error = false;

    /**
     * Creates new form Anadir_cliente
     */
    public Anadir_cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t_name = new javax.swing.JTextField();
        t_apellido = new javax.swing.JTextField();
        t_dni = new javax.swing.JTextField();
        n_edad = new javax.swing.JSpinner();
        v_anadir = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Añadir cliente");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellido");

        jLabel4.setText("DNI:");

        jLabel5.setText("Edad:");

        t_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_nameFocusGained(evt);
            }
        });

        t_apellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_apellidoFocusGained(evt);
            }
        });

        t_dni.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_dniFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                try {
                    t_dniFocusLost(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        n_edad.setMinimumSize(new java.awt.Dimension(84, 22));
        n_edad.setPreferredSize(new java.awt.Dimension(84, 22));
        n_edad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                n_edadFocusGained(evt);
            }
        });

        v_anadir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        v_anadir.setText("Añadir ");
        v_anadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_anadirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(t_apellido))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(t_name, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(169, 169, 169)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(v_anadir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel1)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(t_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(t_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(t_dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(n_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(90, 90, 90)
                .addComponent(v_anadir, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void v_anadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_anadirActionPerformed
        // TODO add your handling code here:
        int cont = 0;
        if(t_name.getText().isEmpty() ){
            cont++;
            t_name.setBorder(new LineBorder(Color.red,1));
        }
        if(t_apellido.getText().isEmpty() ){
            cont++;
            t_apellido.setBorder(new LineBorder(Color.red,1));
        }
        if(t_dni.getText().isEmpty() ){
            cont++;
            t_dni.setBorder(new LineBorder(Color.red,1));
        }
        if(n_edad.getValue().toString().equals('0') ){
            cont++;
            n_edad.setBorder(new LineBorder(Color.red,1));
        }
        
        if (cont == 0 && !error) {
            Cliente c = new Cliente(t_name.getText(), t_apellido.getText(),t_dni.getText(), Integer.parseInt(n_edad.getValue().toString()));
            ProyectoNetBean.insertCliente(c);
        }
        else{
            JOptionPane.showMessageDialog(null, "Revisa los datos");

        }
    }//GEN-LAST:event_v_anadirActionPerformed

    private void t_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_nameFocusGained
        // TODO add your handling code here:
        t_name.setBorder(new LineBorder(Color.black,1));

    }//GEN-LAST:event_t_nameFocusGained

    private void t_apellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_apellidoFocusGained
        // TODO add your handling code here:
        t_apellido.setBorder(new LineBorder(Color.black,1));

    }//GEN-LAST:event_t_apellidoFocusGained

    private void t_dniFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_dniFocusGained
        // TODO add your handling code here:          
        t_dni.setBorder(new LineBorder(Color.black,1));
        t_dni.setForeground(Color.black);

        t_dni.setText("");

        
    }//GEN-LAST:event_t_dniFocusGained

    private void n_edadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_n_edadFocusGained
        // TODO add your handling code here:  
        n_edad.setBorder(new LineBorder(Color.black,1));

    }//GEN-LAST:event_n_edadFocusGained

    private void t_dniFocusLost(java.awt.event.FocusEvent evt) throws SQLException {//GEN-FIRST:event_t_dniFocusLost
        // TODO add your handling code here:
        String dni = t_dni.getText();
        error = ProyectoNetBean.getDni(dni);
        if (error){
            t_dni.setBorder(new LineBorder(Color.red,1));
            t_dni.setText("DNI ya utilizado");
            t_dni.setForeground(Color.red);

        }
    }//GEN-LAST:event_t_dniFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSpinner n_edad;
    private javax.swing.JTextField t_apellido;
    private javax.swing.JTextField t_dni;
    private javax.swing.JTextField t_name;
    private javax.swing.JButton v_anadir;
    // End of variables declaration//GEN-END:variables
}
