/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyectonetbean.Ventanas.PanelesGestion;

import com.mycompany.proyectonetbean.Clases.Cliente;
import com.mycompany.proyectonetbean.Clases.Espectaculo;
import com.mycompany.proyectonetbean.ProyectoNetBean;

import javax.swing.border.LineBorder;
import java.awt.*;
import java.sql.SQLException;
import java.util.ArrayList;

/**
 *
 * @author mario
 */
public class Ver_espectaculo extends javax.swing.JPanel {

    /**
     * Creates new form Ver_espectaculo
     */
    public Ver_espectaculo() {
        initComponents();
        ProyectoNetBean.getEspectaculostoComboBox(cb_espectaculos);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cb_espectaculos = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        t_lugar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        n_coste = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        t_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        n_aforo = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        b_guardar = new javax.swing.JButton();
        b_udpate_espec = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_desc = new javax.swing.JTextArea();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Ver espectaculos");

        jLabel2.setText("Selecciona un espectaculo:");

        cb_espectaculos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                try {
                    cb_espectaculosItemStateChanged(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jLabel5.setText("Lugar:");

        t_lugar.setEnabled(false);

        jLabel6.setText("Coste:");

        n_coste.setEnabled(false);
        n_coste.setMinimumSize(new java.awt.Dimension(124, 22));
        n_coste.setPreferredSize(new java.awt.Dimension(85, 22));

        jLabel3.setText("Nombre:");

        t_name.setEnabled(false);

        jLabel4.setText("Aforo:");

        n_aforo.setEnabled(false);
        n_aforo.setMinimumSize(new java.awt.Dimension(124, 22));
        n_aforo.setPreferredSize(new java.awt.Dimension(85, 22));

        jLabel7.setText("Descripcion:");

        b_guardar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_guardar.setText("Editar");
        b_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_guardarActionPerformed(evt);
            }
        });

        b_udpate_espec.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_udpate_espec.setText("Guardar");
        b_udpate_espec.setEnabled(false);
        b_udpate_espec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_udpate_especActionPerformed(evt);
            }
        });

        ta_desc.setColumns(20);
        ta_desc.setRows(5);
        jScrollPane1.setViewportView(ta_desc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(473, 473, 473)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(jLabel2)
                        .addGap(27, 27, 27)
                        .addComponent(cb_espectaculos, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(367, 367, 367)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(n_coste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(t_name)
                                        .addComponent(n_aforo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(t_lugar, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(b_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(30, 30, 30)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(373, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(632, Short.MAX_VALUE)
                    .addComponent(b_udpate_espec, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(296, 296, 296)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cb_espectaculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(t_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(n_aforo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel7)
                        .addGap(68, 68, 68))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(t_lugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(n_coste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(b_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(473, Short.MAX_VALUE)
                    .addComponent(b_udpate_espec, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(42, 42, 42)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_guardarActionPerformed
        // TODO add your handling code here:
        t_name.setEnabled(true);
        n_aforo.setEnabled(true);
        ta_desc.setEnabled(true);
        t_lugar.setEnabled(true);
        n_coste.setEnabled(true);
        b_udpate_espec.setEnabled(true);
    }//GEN-LAST:event_b_guardarActionPerformed

    private void b_udpate_especActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_udpate_especActionPerformed
        // TODO add your handling code here:
        int cont = 0;
        if (t_name.getText().isEmpty()) {
            cont++;
            t_name.setBorder(new LineBorder(Color.red, 1));
        }
        if (t_lugar.getText().isEmpty()) {
            cont++;
            t_lugar.setBorder(new LineBorder(Color.red, 1));
        }
        if (ta_desc.getText().toString().isEmpty()) {
            cont++;
            ta_desc.setBorder(new LineBorder(Color.red, 1));
        }
        if (n_aforo.getValue().toString().equals('0')) {
            cont++;
            n_aforo.setBorder(new LineBorder(Color.red, 1));
        }

        Espectaculo espectaculo = null;
        if (cont == 0) {
            espectaculo = new Espectaculo(t_name.getText(), Integer.parseInt(n_aforo.getValue().toString()), ta_desc.getText(), t_lugar.getText(), Integer.parseInt(n_coste.getValue().toString()));
            String selectedValue = cb_espectaculos.getSelectedItem().toString();
            String id = selectedValue.split("-")[0];
            espectaculo.setId(id);
        }

        ProyectoNetBean.updateEspectaculo(espectaculo);

        cb_espectaculos.removeAllItems();
        ProyectoNetBean.getEspectaculostoComboBox(cb_espectaculos);
    }//GEN-LAST:event_b_udpate_especActionPerformed

    private void cb_espectaculosItemStateChanged(java.awt.event.ItemEvent evt) throws SQLException {//GEN-FIRST:event_cb_espectaculosItemStateChanged
        // TODO add your handling code here:
        if(cb_espectaculos.getItemCount() > 0){
            String selectedValue = cb_espectaculos.getSelectedItem().toString();
            String id = selectedValue.split("-")[0];
            Espectaculo espectaculo = null;
            espectaculo = ProyectoNetBean.getEspectaculoByID(id);

            t_name.setEnabled(false);
            n_aforo.setEnabled(false);
            ta_desc.setEnabled(false);
            t_lugar.setEnabled(false);
            n_coste.setEnabled(false);
            b_udpate_espec.setEnabled(false);

            t_name.setText( espectaculo.getNombre());
            t_lugar.setText( espectaculo.getLugar());
            ta_desc.setText( espectaculo.getDescripcion());
            n_aforo.setValue( espectaculo.getAforo());
            n_coste.setValue( espectaculo.getCoste());
        }




    }//GEN-LAST:event_cb_espectaculosItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_guardar;
    private javax.swing.JButton b_udpate_espec;
    private javax.swing.JComboBox<String> cb_espectaculos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner n_aforo;
    private javax.swing.JSpinner n_coste;
    private javax.swing.JTextField t_lugar;
    private javax.swing.JTextField t_name;
    private javax.swing.JTextArea ta_desc;
    // End of variables declaration//GEN-END:variables
}
