/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyectonetbean.Ventanas.PanelesGestion;

import com.mycompany.proyectonetbean.Clases.Cliente;
import com.mycompany.proyectonetbean.Clases.Espectaculo;
import com.mycompany.proyectonetbean.ProyectoNetBean;
import java.awt.Color;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author mario
 */
public class Ver_cliente extends javax.swing.JPanel {

    /**
     * Creates new form Ver_cliente
     */
    public Ver_cliente() {
        initComponents();
        ProyectoNetBean.getClientestoComboBox(cb_cliente);
        ProyectoNetBean.getEspectaculostoComboBox(cb_espectaculos);



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t_name = new javax.swing.JTextField();
        t_apellido = new javax.swing.JTextField();
        t_dni = new javax.swing.JTextField();
        n_edad = new javax.swing.JSpinner();
        b_edit_cliente = new javax.swing.JButton();
        b_update_cliente = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cb_cliente = new javax.swing.JComboBox<>();
        b_anadir_a_espectaculo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cb_espectaculos = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        l_espectaculos = new javax.swing.JList<>();

        setPreferredSize(new java.awt.Dimension(1071, 585));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Datos cliente");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellido");

        jLabel4.setText("DNI:");

        jLabel5.setText("Edad:");

        t_name.setEnabled(false);
        t_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_nameFocusGained(evt);
            }
        });
        t_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_nameActionPerformed(evt);
            }
        });

        t_apellido.setEnabled(false);
        t_apellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_apellidoFocusGained(evt);
            }
        });

        t_dni.setEnabled(false);

        n_edad.setEnabled(false);
        n_edad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                n_edadFocusGained(evt);
            }
        });

        b_edit_cliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_edit_cliente.setText("Editar datos");
        b_edit_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_edit_clienteActionPerformed(evt);
            }
        });

        b_update_cliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_update_cliente.setText("Guardar");
        b_update_cliente.setEnabled(false);
        b_update_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_update_clienteActionPerformed(evt);
            }
        });

        jLabel6.setText("Selecciona el cliente:");

        cb_cliente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                try {
                    cb_clienteItemStateChanged(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });
        cb_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_clienteActionPerformed(evt);
            }
        });

        b_anadir_a_espectaculo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_anadir_a_espectaculo.setText("Añadir a espectaculo");
        b_anadir_a_espectaculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_anadir_a_espectaculoActionPerformed(evt);
            }
        });

        jLabel7.setText("Espectaculos");

        cb_espectaculos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_espectaculosItemStateChanged(evt);
            }
        });
        cb_espectaculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_espectaculosActionPerformed(evt);
            }
        });

        l_espectaculos.setEnabled(false);
        jScrollPane1.setViewportView(l_espectaculos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(t_name, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jLabel4)
                .addGap(24, 24, 24)
                .addComponent(t_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(t_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(n_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(b_edit_cliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b_update_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cb_espectaculos, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(b_anadir_a_espectaculo)))
                        .addContainerGap(108, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(jLabel6)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(cb_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cb_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(t_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(b_edit_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(t_dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(t_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(n_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(b_update_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel7)
                        .addGap(29, 29, 29)
                        .addComponent(cb_espectaculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(b_anadir_a_espectaculo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_edit_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_edit_clienteActionPerformed
        // TODO add your handling code here:
        t_name.setEnabled(true);        
        t_apellido.setEnabled(true);      
        n_edad.setEnabled(true);
        b_update_cliente.setEnabled(true);


    }//GEN-LAST:event_b_edit_clienteActionPerformed

    private void b_update_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_update_clienteActionPerformed
        // TODO add your handling code here:
        int cont = 0;
        if(t_name.getText().isEmpty() ){
            cont++;
            t_name.setBorder(new LineBorder(Color.red,1));
        }
        if(t_apellido.getText().isEmpty() ){
            cont++;
            t_apellido.setBorder(new LineBorder(Color.red,1));
        }
        if(n_edad.getValue().toString().equals('0') ){
            cont++;
            n_edad.setBorder(new LineBorder(Color.red,1));
        }
        
        if (cont == 0) {
            Cliente c = new Cliente(t_name.getText(), t_apellido.getText(),t_dni.getText(), Integer.parseInt(n_edad.getValue().toString()));
            String selectedValue = cb_cliente.getSelectedItem().toString();
            String id = selectedValue.split("-")[0];
            c.setId(id);

            ProyectoNetBean.updateCliente(c);
            cb_cliente.removeAllItems();
            ProyectoNetBean.getClientestoComboBox(cb_cliente);
        }
        else{
            JOptionPane.showMessageDialog(null, "Revisa los datos");

        }
    }//GEN-LAST:event_b_update_clienteActionPerformed

    private void cb_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_clienteActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cb_clienteActionPerformed

    private void cb_clienteItemStateChanged(java.awt.event.ItemEvent evt) throws SQLException {//GEN-FIRST:event_cb_clienteItemStateChanged
        // TODO add your handling code here:
        if(cb_cliente.getItemCount() > 0){
            String selectedValue = cb_cliente.getSelectedItem().toString();
            String id = selectedValue.split("-")[0];
            Cliente cliente = ProyectoNetBean.getClienteByID(id);
            System.out.println(cliente.getApellido());

            ProyectoNetBean.getEspectaculosOfCliente(l_espectaculos,id);


            t_name.setText(cliente.getNombre());
            t_apellido.setText(cliente.getApellido());
            t_dni.setText(cliente.getDni());
            n_edad.setValue(cliente.getEdad());

            t_name.setEnabled(false);
            t_apellido.setEnabled(false);
            n_edad.setEnabled(false);
            n_edad.setEnabled(false);
        }

    }//GEN-LAST:event_cb_clienteItemStateChanged

    private void t_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_nameActionPerformed

    private void t_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_nameFocusGained
        // TODO add your handling code here:
        t_name.setBorder(new LineBorder(Color.black,1));

    }//GEN-LAST:event_t_nameFocusGained

    private void t_apellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_apellidoFocusGained
        // TODO add your handling code here:
        t_apellido.setBorder(new LineBorder(Color.black,1));

    }//GEN-LAST:event_t_apellidoFocusGained

    private void n_edadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_n_edadFocusGained
        // TODO add your handling code here:
        n_edad.setBorder(new LineBorder(Color.black,1));

    }//GEN-LAST:event_n_edadFocusGained

    private void b_anadir_a_espectaculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_anadir_a_espectaculoActionPerformed
        // TODO add your handling code here:
        String selectedValueCliente = cb_cliente.getSelectedItem().toString();
        String idCliente = selectedValueCliente.split("-")[0];
        
         String selectedValueEspectaculo = cb_espectaculos.getSelectedItem().toString();
        String idEspectaculo = selectedValueEspectaculo.split("-")[0];

        ProyectoNetBean.addClienteToEspectaculo( idCliente,  idEspectaculo);
    }//GEN-LAST:event_b_anadir_a_espectaculoActionPerformed

    private void cb_espectaculosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_espectaculosItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_espectaculosItemStateChanged

    private void cb_espectaculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_espectaculosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_espectaculosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_anadir_a_espectaculo;
    private javax.swing.JButton b_edit_cliente;
    private javax.swing.JButton b_update_cliente;
    private javax.swing.JComboBox<String> cb_cliente;
    private javax.swing.JComboBox<String> cb_espectaculos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> l_espectaculos;
    private javax.swing.JSpinner n_edad;
    private javax.swing.JTextField t_apellido;
    private javax.swing.JTextField t_dni;
    private javax.swing.JTextField t_name;
    // End of variables declaration//GEN-END:variables
}
