/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyectonetbean.Ventanas;
import com.mycompany.proyectonetbean.ProyectoNetBean;
/**
 *
 * @author 8fdam02
 */
public class Anadir_cliente_a_espectaculo extends javax.swing.JPanel {

    /**
     * Creates new form Anadir_cliente_a_espectaculo
     */
    String idCliente;
    public Anadir_cliente_a_espectaculo(String idCliente) {
        this.idCliente = idCliente;
        initComponents();
        ProyectoNetBean.getEspectaculostoComboBox(cb_espectaculo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cb_espectaculo = new javax.swing.JComboBox<>();
        b_anadir = new javax.swing.JButton();

        jLabel1.setText("Añadir cliente a espectaculo:");

        cb_espectaculo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_espectaculoItemStateChanged(evt);
            }
        });

        b_anadir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_anadir.setText("Añadir");
        b_anadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_anadirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(cb_espectaculo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(125, 125, 125)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(b_anadir)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(cb_espectaculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(b_anadir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cb_espectaculoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_espectaculoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_espectaculoItemStateChanged

    private void b_anadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_anadirActionPerformed
        // TODO add your handling code here:
        String selectedValue = cb_espectaculo.getSelectedItem().toString();
        String id = selectedValue.split("-")[0];

        
        ProyectoNetBean.addClienteToEspectaculo(idCliente,id);
    }//GEN-LAST:event_b_anadirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_anadir;
    private javax.swing.JComboBox<String> cb_espectaculo;
    private javax.swing.JLabel jLabel1;


    // End of variables declaration//GEN-END:variables
}
