/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectonetbean.Ventanas;
import com.mycompany.proyectonetbean.ProyectoNetBean;
import com.mycompany.proyectonetbean.Ventanas.PanelesGestion.*;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author 8fdam02
 */
public class Ventana_gestion extends javax.swing.JFrame {

    /**
     * Creates new form EspectaculosParque
     */
    public Ventana_gestion() {
        initComponents();
        visualizar_espectaculos(desktop);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_Espectaculos = new javax.swing.JMenu();
        m_espec_disponibles = new javax.swing.JMenuItem();
        m_espec_anadir = new javax.swing.JMenuItem();
        m_espec_borrar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        m_cliente_ver = new javax.swing.JMenuItem();
        m_cliente_anadir = new javax.swing.JMenuItem();
        m_cliente_borrar = new javax.swing.JMenuItem();
        m_empleado = new javax.swing.JMenu();
        ver_empleados = new javax.swing.JMenuItem();
        m_emple_anadir = new javax.swing.JMenuItem();
        m_emple_borrar = new javax.swing.JMenuItem();
        m_metadatos = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        menu_Espectaculos.setText("Espectaculos");

        m_espec_disponibles.setText("Visualizar");
        m_espec_disponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_espec_disponiblesActionPerformed(evt);
            }
        });
        menu_Espectaculos.add(m_espec_disponibles);

        m_espec_anadir.setText("Añadir");
        m_espec_anadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_espec_anadirActionPerformed(evt);
            }
        });
        menu_Espectaculos.add(m_espec_anadir);

        m_espec_borrar.setText("Borrar");
        m_espec_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_espec_borrarActionPerformed(evt);
            }
        });
        menu_Espectaculos.add(m_espec_borrar);

        jMenuBar1.add(menu_Espectaculos);

        jMenu2.setText("Clientes");

        m_cliente_ver.setText("Visualizar");
        m_cliente_ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_cliente_verActionPerformed(evt);
            }
        });
        jMenu2.add(m_cliente_ver);

        m_cliente_anadir.setText("Añadir");
        m_cliente_anadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_cliente_anadirActionPerformed(evt);
            }
        });
        jMenu2.add(m_cliente_anadir);

        m_cliente_borrar.setText("Borrar");
        m_cliente_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_cliente_borrarActionPerformed(evt);
            }
        });
        jMenu2.add(m_cliente_borrar);

        jMenuBar1.add(jMenu2);

        m_empleado.setText("Empleados");

        ver_empleados.setText("Visualizar");
        ver_empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ver_empleadosActionPerformed(evt);
            }
        });
        m_empleado.add(ver_empleados);

        m_emple_anadir.setText("Añadir");
        m_emple_anadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_emple_anadirActionPerformed(evt);
            }
        });
        m_empleado.add(m_emple_anadir);

        m_emple_borrar.setText("Borrar");
        m_emple_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_emple_borrarActionPerformed(evt);
            }
        });
        m_empleado.add(m_emple_borrar);

        jMenuBar1.add(m_empleado);

        m_metadatos.setText("Metadatos");
        m_metadatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_metadatosActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Metadatos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        m_metadatos.add(jMenuItem1);

        jMenuBar1.add(m_metadatos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(872, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void m_cliente_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_cliente_borrarActionPerformed
        // TODO add your handling code here:
        Borrar_cliente borrar_cliente = new Borrar_cliente();
        borrar_cliente.setSize(1071,585);
        borrar_cliente.setLocation(0,0);
        desktop.removeAll();
        desktop.add(borrar_cliente,BorderLayout.CENTER);
        desktop.revalidate();
        desktop.repaint();
    }//GEN-LAST:event_m_cliente_borrarActionPerformed

    private void m_espec_anadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_espec_anadirActionPerformed
        // TODO add your handling code here:
        Anadir_espectaculo new_espectaculo = new Anadir_espectaculo();
        new_espectaculo.setSize(1071,585);
        new_espectaculo.setLocation(0,0);
        desktop.removeAll();
        desktop.add(new_espectaculo,BorderLayout.CENTER);
        desktop.revalidate();
        desktop.repaint();
    }//GEN-LAST:event_m_espec_anadirActionPerformed

    private void m_espec_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_espec_borrarActionPerformed
        // TODO add your handling code here:
        Borrar_espectaculo borrar_espectaculo = new Borrar_espectaculo();
        borrar_espectaculo.setSize(1071,585);
        borrar_espectaculo.setLocation(0,0);
        desktop.removeAll();
        desktop.add(borrar_espectaculo,BorderLayout.CENTER);
        desktop.revalidate();
        desktop.repaint();
    }//GEN-LAST:event_m_espec_borrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ProyectoNetBean.Cancelar(this);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void m_espec_disponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_espec_disponiblesActionPerformed
        // TODO add your handling code here:
        visualizar_espectaculos(desktop);
    }//GEN-LAST:event_m_espec_disponiblesActionPerformed

    private void m_cliente_verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_cliente_verActionPerformed
        // TODO add your handling code here:
        Ver_cliente ver_cliente = new Ver_cliente();
        ver_cliente.setSize(1071,585);
        ver_cliente.setLocation(0,0);
        desktop.removeAll();
        desktop.add(ver_cliente,BorderLayout.CENTER);
        desktop.revalidate();
        desktop.repaint();
        
    }//GEN-LAST:event_m_cliente_verActionPerformed

    private void m_cliente_anadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_cliente_anadirActionPerformed
        // TODO add your handling code here:
        Anadir_cliente anadir_cliente = new Anadir_cliente();
        anadir_cliente.setSize(1071,585);
        anadir_cliente.setLocation(0,0);
        desktop.removeAll();
        desktop.add(anadir_cliente,BorderLayout.CENTER);
        desktop.revalidate();
        desktop.repaint();
    }//GEN-LAST:event_m_cliente_anadirActionPerformed

    private void ver_empleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ver_empleadosActionPerformed
        // TODO add your handling code here:
        Ver_empleado ver_mepleado = new Ver_empleado();
        ver_mepleado.setSize(1071,585);
        ver_mepleado.setLocation(0,0);
        desktop.removeAll();
        desktop.add(ver_mepleado,BorderLayout.CENTER);
        desktop.revalidate();
        desktop.repaint();
    }//GEN-LAST:event_ver_empleadosActionPerformed

    private void m_emple_anadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_emple_anadirActionPerformed
        // TODO add your handling code here:
        Anadir_empleado anadir_mepleado = new Anadir_empleado();
        anadir_mepleado.setSize(1071,585);
        anadir_mepleado.setLocation(0,0);
        desktop.removeAll();
        desktop.add(anadir_mepleado,BorderLayout.CENTER);
        desktop.revalidate();
        desktop.repaint();
    }//GEN-LAST:event_m_emple_anadirActionPerformed

    private void m_emple_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_emple_borrarActionPerformed
        // TODO add your handling code here:
        Borrar_empleado borrar_mepleado = new Borrar_empleado();
        borrar_mepleado.setSize(1071,585);
        borrar_mepleado.setLocation(0,0);
        desktop.removeAll();
        desktop.add(borrar_mepleado,BorderLayout.CENTER);
        desktop.revalidate();
        desktop.repaint();
    }//GEN-LAST:event_m_emple_borrarActionPerformed

    private void m_metadatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_metadatosActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_m_metadatosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Show_metadatos show_metadatos = new Show_metadatos();
        show_metadatos.setSize(1071,585);
        show_metadatos.setLocation(0,0);
        desktop.removeAll();
        desktop.add(show_metadatos,BorderLayout.CENTER);
        desktop.revalidate();
        desktop.repaint();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_gestion().setVisible(true);
            }
        });
    }
    public static void visualizar_espectaculos(JPanel desktop){
        Ver_espectaculo ver_espectaculo = new Ver_espectaculo();
        ver_espectaculo.setSize(1071,585);
        ver_espectaculo.setLocation(0,0);
        desktop.removeAll();
        desktop.add(ver_espectaculo,BorderLayout.CENTER);
        desktop.revalidate();
        desktop.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel desktop;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem m_cliente_anadir;
    private javax.swing.JMenuItem m_cliente_borrar;
    private javax.swing.JMenuItem m_cliente_ver;
    private javax.swing.JMenuItem m_emple_anadir;
    private javax.swing.JMenuItem m_emple_borrar;
    private javax.swing.JMenu m_empleado;
    private javax.swing.JMenuItem m_espec_anadir;
    private javax.swing.JMenuItem m_espec_borrar;
    private javax.swing.JMenuItem m_espec_disponibles;
    private javax.swing.JMenu m_metadatos;
    private javax.swing.JMenu menu_Espectaculos;
    private javax.swing.JMenuItem ver_empleados;
    // End of variables declaration//GEN-END:variables
}
